//
// Created by Tristan Brindle on 24/10/2017.
//

#ifndef CPP_LONDON_UNI_EXERCISE2_HPP
#define CPP_LONDON_UNI_EXERCISE2_HPP

#include <string>

// Requirements:
//   -- given an uppercase character A-Z, shifts that character by 13 places
//   -- spaces, numbers and punctuation should not be changed
char shift_char(char c);

// Requirements:
//   -- given a string consisting of uppercase characters and punctuation,
//      returns a new string with each character shifted by 13 places
//   -- spaces, numbers and punctuation should not be changed
std::string rot13(std::string str);

// Requirements:
//   -- given a string consisting of uppercase characters and punctuation,
//      returns a new string with each character shifted by n places
std::string encode(std::string str, int n = 13);

// Requirements:
//   -- given a string generated by encode(str, n), returns the original string
std::string decode(std::string str, int n = 13);

#endif
